_wandb:
    value:
        cli_version: 0.24.0
        e:
            ceyyl92euf49ta2xkbtkmjqfmi065poy:
                args:
                    - --node-ip-address=202.120.38.31
                    - --node-manager-port=35843
                    - --object-store-name=/tmp/ray/session_2026-01-27_10-39-45_779047_754533/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2026-01-27_10-39-45_779047_754533/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=57329
                    - --runtime-env-agent-port=56835
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=56835
                    - --gcs-address=202.120.38.31:41379
                    - --session-name=session_2026-01-27_10-39-45_779047_754533
                    - --temp-dir=/tmp/ray
                    - --webui=
                    - --cluster-id=624c11b517fca2ab848baf772582dff995074feb9f7d572d55bdb371
                    - --startup-token=192
                    - --worker-launch-time-ms=1769481588009
                    - --node-id=ac2134e67aebb92c29d7abc6567db9dadf0f609766e5cb6caaf50c8f
                    - --runtime-env-hash=1830736042
                cpu_count: 96
                cpu_count_logical: 192
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1888559353856"
                        used: "203281084416"
                email: 2319622989@qq.com
                executable: /home/lantu/.conda/envs/guir1/bin/python3
                git:
                    commit: d43eea2f1c52356077034ff2524642fc05e06c6a
                    remote: git@github.com:ritzz-ai/GUI-R1.git
                gpu: NVIDIA RTX 6000 Ada Generation
                gpu_count: 6
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-7ad5c3eb-adf0-f70a-e670-8438701a553e
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-9630f0c1-163a-1dc7-564b-8242ac677a1e
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-177e688f-b5f1-1713-0c2e-29d927a058b3
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-061bb9ea-eff0-d537-2c5c-0d4b99e7c5b0
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-952f56b5-261e-aa03-6546-8e690d63c3fe
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-9aceb2db-80ad-104a-718a-2575f9270204
                host: qwe-AS-4125GS-TNRT
                memory:
                    total: "2425154666496"
                os: Linux-6.11.0-snp-host-557bec581802+-x86_64-with-glibc2.39
                program: /home/lantu/.conda/envs/guir1/lib/python3.10/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.10.19
                root: /home/lantu/GUIattack/GUI-R1
                startedAt: "2026-01-27T02:41:06.216839Z"
                writerId: ceyyl92euf49ta2xkbtkmjqfmi065poy
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 51
                - 71
                - 95
                - 105
            "2":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 51
                - 71
                - 95
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.19
            "5": 0.24.0
            "6": 4.49.0
            "12": 0.24.0
            "13": linux-x86_64
algorithm:
    value:
        adv_estimator: grpo
        disable_kl: false
        gamma: 1
        kl_coef: 0.01
        kl_horizon: 0
        kl_penalty: low_var_kl
        kl_target: 0
        kl_type: fixed
        lam: 1
        use_kl_loss: true
data:
    value:
        answer_key: answer
        image_key: images
        max_pixels: 1258291
        max_prompt_length: 2048
        max_response_length: 1024
        min_pixels: 262144
        prompt_key: problem
        rollout_batch_size: 32
        seed: 1
        shuffle: true
        system_prompt: null
        train_files: /data2/lt/dataset/ritzzai/GUI-R1/train.parquet
        val_batch_size: 8
        val_files: /data2/lt/dataset/ritzzai/GUI-R1/test.parquet
trainer:
    value:
        critic_warmup: 0
        experiment_name: qwen2_5_vl_3b_guir1_grpo
        load_checkpoint_path: null
        logger:
            - console
            - wandb
        max_steps: null
        n_gpus_per_node: 1
        nnodes: 1
        project_name: easy_r1
        save_checkpoint_path: checkpoints/easy_r1/qwen2_5_vl_3b_guir1_grpo
        save_freq: 5
        save_limit: 3
        total_episodes: 15
        val_before_train: true
        val_freq: 5
        val_generations_to_log: 1
        val_only: false
worker:
    value:
        actor:
            clip_ratio: 0.2
            disable_kl: false
            fsdp:
                enable_cpu_offload: false
                enable_full_shard: false
                enable_rank0_init: true
                fsdp_size: -1
                mp_buffer_dtype: fp32
                mp_param_dtype: bf16
                mp_reduce_dtype: fp32
                torch_dtype: null
                use_orig_params: false
            global_batch_size: 1
            global_batch_size_per_device: -1
            kl_coef: 0.01
            kl_penalty: low_var_kl
            max_grad_norm: 1
            micro_batch_size_per_device_for_experience: 1
            micro_batch_size_per_device_for_update: 1
            model:
                enable_gradient_checkpointing: true
                freeze_vision_tower: false
                model_path: /data2/lt/model/Qwen/Qwen-2.5-VL-3B-Instruct
                tokenizer_path: /data2/lt/model/Qwen/Qwen-2.5-VL-3B-Instruct
                trust_remote_code: false
            offload:
                offload_optimizer: true
                offload_params: true
            optim:
                betas:
                    - 0.9
                    - 0.999
                lr: 1e-06
                lr_warmup_ratio: 0
                min_lr_ratio: null
                strategy: adamw
                training_steps: 1665
                warmup_style: constant
                weight_decay: 0.01
            padding_free: true
            ppo_epochs: 1
            strategy: fsdp
            ulysses_sequence_parallel_size: 1
            use_kl_loss: true
            use_torch_compile: true
        critic:
            cliprange_value: 0.5
            fsdp:
                enable_cpu_offload: false
                enable_full_shard: true
                enable_rank0_init: false
                fsdp_size: -1
                mp_buffer_dtype: fp32
                mp_param_dtype: bf16
                mp_reduce_dtype: fp32
                torch_dtype: null
                use_orig_params: false
            global_batch_size: 256
            global_batch_size_per_device: -1
            max_grad_norm: 1
            micro_batch_size_per_device_for_experience: 16
            micro_batch_size_per_device_for_update: 4
            model:
                enable_gradient_checkpointing: true
                freeze_vision_tower: false
                model_path: null
                tokenizer_path: null
                trust_remote_code: true
            offload:
                offload_optimizer: false
                offload_params: false
            optim:
                betas:
                    - 0.9
                    - 0.999
                lr: 1e-06
                lr_warmup_ratio: 0
                min_lr_ratio: null
                strategy: adamw
                training_steps: 1665
                warmup_style: constant
                weight_decay: 0.01
            padding_free: false
            ppo_epochs: 1
            strategy: fsdp
            ulysses_sequence_parallel_size: 1
        hybrid_engine: true
        ref:
            fsdp:
                enable_cpu_offload: true
                enable_full_shard: true
                enable_rank0_init: true
                fsdp_size: -1
                mp_buffer_dtype: fp32
                mp_param_dtype: bf16
                mp_reduce_dtype: fp32
                torch_dtype: null
                use_orig_params: false
            micro_batch_size_per_device_for_experience: 1
            offload:
                offload_optimizer: false
                offload_params: false
            padding_free: true
            strategy: fsdp
            ulysses_sequence_parallel_size: 1
            use_torch_compile: true
        reward:
            compute_score: r1gui
            reward_type: function
        rollout:
            disable_log_stats: true
            dtype: bf16
            enable_chunked_prefill: false
            enforce_eager: false
            free_cache_engine: false
            gpu_memory_utilization: 0.3
            ignore_eos: false
            limit_images: 0
            max_num_batched_tokens: 8192
            max_num_seqs: 1024
            "n": 2
            name: vllm
            prompt_length: 2048
            response_length: 1024
            temperature: 1
            tensor_parallel_size: 1
            top_k: -1
            top_p: 1
            val_override_config:
                "n": 1
                temperature: 0.5
